stages:
  - build
  - test
  - package
  - scan
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/hello-world

before_script:
  - apk update && apk add docker
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA

scan_code:
  stage: scan
  script:
    - echo "Running code scanning tools"
    # Example: Integrate with SonarQube or other code scanning tools here

scan_image:
  stage: scan
  script:
    - echo "Scanning Docker image for vulnerabilities"
    # Example: Integrate with Trivy or Clair here

deploy:
  stage: deploy
  script:
    - helm upgrade --install my-java-app ./helm-chart --set image.repository=$DOCKER_IMAGE --set image.tag=$CI_COMMIT_SHORT_SHA

after_script:
  - echo "Deploymentcompleted"
